---
title: "NTDC analysis"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-09-06"
---

```{r, echo=F, message=F, warning=F, results=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
changeCellColor <- function(row, col){
  c(
    "function(row, data, num, index){",
    sprintf("  if(index == %d){", row-1),
    sprintf("    $('td:eq(' + %d + ')', row)", col),
    "    .css({'background-color': 'orange'});",
    "  }",
    "}"  
  )
}
```


```{r, echo=F, message=F, warning=F}
plot_function=function(title, data, legend_rows=1, var_name, num_size=3, legend_text_size=11, y_axis_text=12)
{
  
  x_var <- sym(var_name)  ########## https://stackoverflow.com/questions/4856849/looping-over-variables-in-ggplot this is the key step for the loop 

  
  y_limit=max(data$n)*1.1
g1=ggplot(data, aes(x=!!x_var, y=n, fill=!!x_var)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, y_limit))+
  ylab("n")+xlab("")+
  #theme(legend.position="", legend.title=element_text(size=10))+
  theme(legend.position="bottom", legend.title=element_blank(), legend.text = element_text(size=legend_text_size))+
  theme(axis.text.x = element_blank())+
  theme(axis.text.y = element_text(size = y_axis_text))+
  #geom_text(aes(label=practice_setting2$n), position=position_dodge(width=0.9), vjust=-0.25, size=3)+  # add numbers over bars
  geom_text(label = with(data, paste(n, paste0("(", prop*100, "%", ")"))), vjust=-1, size=num_size)+
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
   guides(fill = guide_legend(nrow = legend_rows))
  return(g1)
}
```




```{r, echo=F, message=F, warning=F}
#file1=read.csv("C:\\Shengtong\\Research\\OralPublicHealth\\NTDC\\NTDC_ClientFile1.csv")
#file2=read.csv("C:\\Shengtong\\Research\\OralPublicHealth\\NTDC\\NTDC_ClientFile2.csv")
#claims_file=read.csv("C:\\Shengtong\\Research\\OralPublicHealth\\NTDC\\NTDC_DENTAL_CLAIMS_FILE.csv")
#save(file1, file2, claims_file, file="C:\\Shengtong\\Research\\OralPublicHealth\\NTDC\\NTDC_data.RData")
load("C:\\Shengtong\\Research\\OralPublicHealth\\NTDC\\NTDC_data.RData")
```

## ids in file 1 and 2 


```{r, message=F, warning=F}
file1_unique_ids=unique(file1$MEDICAID_CLIENT_ID)
file2_unique_ids=unique(file2$MEDICAID_CLIENT_ID)
file1_file2_common_ids=unique(intersect(file1_unique_ids, file2_unique_ids))

grid.newpage() 
draw.pairwise.venn(area1=length(file1_unique_ids), area2=length(file2_unique_ids),cross.area=length(file1_file2_common_ids), 
                   category=c("ClientFile1","ClientFile2"),fill=c("Red","Yellow"))
```
* all 91833 unique `MEDICAID_CLIENT_ID` in ClientFile2 are in ClientFile1, that has 224 more.  


## frequency of column Q by year  

```{r, message=F, warning=F}
last_day_of_service=claims_file$`LAST_DATE_OF_SERVICE`
last_day_of_service_by_year=substr(last_day_of_service, 6, 9)  # extract years  
count_by_year=sapply(sort(unique(last_day_of_service_by_year)), function(x) sum(last_day_of_service_by_year==x))
year_count=data.frame(year=sort(unique(last_day_of_service_by_year)), n=count_by_year) %>% mutate(prop=round(n/sum(count_by_year),4))

fig=plot_function("No. claims by year", year_count, legend_rows = 1, var_name = "year")

fig



year_count %>% 
  datatable(extensions = 'Buttons',
          caption = "", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```
* one patient may have multiple claims 



## year 2022 

```{r, message=F, warning=F}
claims_file_year=claims_file[(grep(claims_file$CLAIM_PAID_DATE, "2022")),]
status=sapply(claims_file$CLAIM_PAID_DATE, function(x) grepl("2022", x))
claims_file_year=claims_file[status, ]
claims_file_year_ids=unique(claims_file_year$CLIENT_ID)
length(claims_file_year_ids)

status=sapply(file2$CLNDR_YR_MONTH, function(x) grepl("2022", x))
file2_year=file2[status, ]
file2_year_ids=unique(file2_year$MEDICAID_CLIENT_ID)
length(file2_year_ids)

#status=sapply(file1$CLNDR_YR_MONTH, function(x) grepl("2022", x))
#file1_year=file1[status, ]
#file1_year_ids=unique(file1_year$MEDICAID_CLIENT_ID)
#length(file1_year_ids)

claim_file2_common_ids_year=intersect(claims_file_year_ids, file2_year_ids)
length(claim_file2_common_ids_year)




grid.newpage() 
draw.pairwise.venn(area1=length(claims_file_year_ids), area2=length(file2_year_ids),cross.area=length(claim_file2_common_ids_year), 
                   category=c("Claim_2022","file2_2022"),fill=c("Red","Yellow"))
```

* for year 2022, claims file has 14830 unique ids,  file2 has 87980 unique ids, with  14759 overlapping with claim file and 71 only in claims file. 

* ClientFile1 doesn't have year 2022 in column `CLNDR_YR_MONTH`. 