---
title: "year 2019"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-05-08"
---

```{r, echo=F, message=F, warning=F, results=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")

```



```{r, message=F, warning=F}
# convter date, e.g. 01OCT2017  -->2017-10-01
convert_date<-function(x)
{
  year=substr(x, 6,9)
  month=substr(x, 3,5)
  if (month=="JAN")
     month="01"
  if (month=="FEB")
     month="02"
  if (month=="MAR")
     month="03"
   if (month=="APR")
     month="04"
   if (month=="MAY")
     month="05"
   if (month=="JUN")
     month="06"
   if (month=="JUL")
     month="07"
   if (month=="AUG")
     month="08"
   if (month=="SEP")
     month="09"
   if (month=="OCT")
     month="10"
   if (month=="NOV")
     month="11"
   if (month=="DEC")
     month="12"
   date=substr(x, 1,2)
  return(paste(year, month, date, sep="-"))
}
```




```{r, echo=F, message=F, warning=F, results=F, eval=F}
#HMO_claims=read.csv("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\HMO Claims\\HMO Claims.csv")
#save(HMO_claims, file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CW Fluoridation Analysis\\HMO Claims\\HMO_claims.RData")
load("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\HMO Claims\\HMO_claims.RData")

#Demographics=multiplesheets("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\Demographics\\Demographics.xlsx")
#Demographics=read.csv("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CW Fluoridation Analysis\\Demographics\\Demographics.csv", header=T)
#saveRDS(Demographics, file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\Demographics\\Demographics.rds")
Demographics=readRDS(file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\Demographics\\Demographics.rds")

#FFS_claim=read.csv("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CW Fluoridation Analysis\\FFS Claims\\FFS Claims.csv", header=T)
#saveRDS(FFS_claim, file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CW Fluoridation Analysis\\FFS Claims\\FFS_Claims.rds")
FFS_claims=readRDS("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\FFS Claims\\FFS_Claims.rds")

####################### extract data at specific year 

hmo_claims_2019=HMO_claims %>% filter(str_detect(FIRST_DATE_OF_SERVICE, "2019"))  # extract individuals with service at year 2019
ffs_claims_2019=FFS_claims %>% filter(str_detect(FIRST_DATE_OF_SERVICE, "2019")) 
#demographics_2019=Demographics %>% filter(str_detect(EFFECTIVE_DATE, "2019"))  # this is not correct
demographics_2019=readRDS("C:\\Users\\hans\\OneDrive - Marquette University\\OralPublicHealth\\demographic_2019.rds")
data_2019=list(demographics_2019=demographics_2019, hmo_claims_2019=hmo_claims_2019, ffs_claims_2019=ffs_claims_2019)
#saveRDS(data_2019, file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\data_year2019.rds")
```


```{r, echo=F, message=F, warning=F, eval=F}
# given an id, calculate its eligibility time period(s)
demographics_ELIGIBILITY_START_DATE=sapply(Demographics$ELIGIBILITY_START_DATE, convert_date)
demographics_ELIGIBILITY_END_DATE=sapply(Demographics$ELIGIBILITY_END_DATE, convert_date)
demographics_eligibiligy=data.frame(id=Demographics$RECIPIENT_ID, demographics_ELIGIBILITY_START_DATE=demographics_ELIGIBILITY_START_DATE, demographics_ELIGIBILITY_END_DATE=demographics_ELIGIBILITY_END_DATE)
demographics_eligibiligy_unique_id=unique(demographics_eligibiligy$id)

###################### check if an id has enrolled dates in 2019
library(lubridate)

check_enrolled_date=function(X)
{
cat(which(demographics_eligibiligy_unique_id==X)," th id is running", ".\n",sep="")

  id_visit=demographics_eligibiligy %>% filter(id ==X)
  
  status_checking=function(Y)
  {
   # if (Y$demographics_ELIGIBILITY_START_DATE>=2019-12-31 || Y$demographics_ELIGIBILITY_END_DATE<=2019-01-01)   # check if this interval crosses year 2019
    if (as.Date(Y[2])<=as.Date("2019-01-01") & as.Date(Y[3])>=as.Date("2019-01-01"))  # check if this interval crosses year 2019
      return(1)
    if (as.Date(Y[2])>=as.Date("2019-01-01") & as.Date(Y[2])<=as.Date("2019-12-31"))   # check if this interval crosses year 2019
      return(1)
    
    if (as.Date(Y[3])<as.Date("2019-01-01"))  # check if this interval crosses year 2019
      return(0)
    if (as.Date(Y[2])>as.Date("2019-12-31"))  # check if this interval crosses year 2019
      return(0)
  }
  
  if (nrow(id_visit)>1)
    status_total=sum(unlist(apply(id_visit, 1, status_checking)))  

  
  if (nrow(id_visit)==1)
  {
    if (as.Date(id_visit[1,2])<=as.Date("2019-01-01") & as.Date(id_visit[1,3])>=as.Date("2019-01-01"))  # check if this interval crosses year 2019
      status_total=1
    if (as.Date(id_visit[1,2])>=as.Date("2019-01-01") & as.Date(id_visit[1,2])<=as.Date("2019-12-31"))   # check if this interval crosses year 2019
      status_total=1
    
    if (as.Date(id_visit[1,3])<as.Date("2019-01-01"))  # check if this interval crosses year 2019
      status_total=0
    if (as.Date(id_visit[1,2])>as.Date("2019-12-31"))  # check if this interval crosses year 2019
      status_total=0

  }
  
  return(ifelse(status_total>0, "Yes", "No"))
}
library(dplyr)
start.time <- Sys.time()

demographic_2019_check=sapply(demographics_eligibiligy_unique_id, check_enrolled_date)
demographic_2019=data.frame(demographics_eligibiligy_unique_id,demographic_2019_check)
end.time <- Sys.time()
time.taken <- round(end.time - start.time,2)
time.taken

#saveRDS(demographic_2019, file="C:\\Users\\hans\\OneDrive - Marquette University\\OralPublicHealth\\demographic_2019.rds")


```


## unique ids  

```{r, message=F, warning=F}
data_year2019=readRDS("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\data_year2019.rds")
```

* numbers for benchmarking 

```
2017 (n = 803 659)

Male 363 814 (45.3) Female 439 845 (54.7)

2018 (n = 796 162)

Male 361 588 (45.4) Female 434 574 (54.6)

2019 (n = 786 095)

Male 356 983 (45.4) Female 429 112 (54.6)

2020 (n = 792 777)

Male 361 723 (45.6) Female 431 054 (54.4)
```


```{r, message=F, warning=F}

#data_2019$demographics_2019 %>% filter(demographic_2019_check=="Yes") %>% nrow()  # 1612620
#length(unique(data_year2019$hmo_claims_2019$RECIPIENT_ID)) # 56763
#length(unique(data_year2019$ffs_claims_2019$RECIPIENT_ID)) # 59361

ggplot(data.frame(source=c( "Demographs", "HMO claims", "FFS claims"), num=c(1612620, 56763, 59361)), aes(x=source, y=num, fill=source))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("No. unique ids")+
 #  ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=10))+
   ggtitle("year 2019")+
   geom_text(aes(label=num), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
  #geom_signif(annotations ="p=0.074", y_position = 0.52  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=3.5, color="black")+ # textsize is for text over the bar; size is for width of lines 
  # geom_signif(annotations ="p<0.001", y_position = 0.59  ,xmin=1, xmax=3, size=1, vjust=-0.5, textsize=3.5, color="red")+
  #geom_signif(annotations ="p<0.001", y_position = 0.86  ,xmin=1, xmax=4, size=1, vjust=-0.5, textsize=3.5, color="red")+
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())+
  theme(legend.position = "none")
```

* ffs: first service date in 2019

* hmo: first service date in 2019

* demographics: ids that have eligibility date in 2019


```{r, message=F, warning=F}
demographic_2019_id=data_year2019$demographics_2019 %>% filter(demographic_2019_check=="Yes") %>% select(demographics_eligibiligy_unique_id) %>% pull()
#length(unique(intersect(demographic_2019_id, data_year2019$ffs_claims_2019$RECIPIENT_ID))) # 59360
#length(unique(intersect(demographic_2019_id, data_year2019$hmo_claims_2019$RECIPIENT_ID))) # 56763
#length(unique(intersect(data_year2019$hmo_claims_2019$RECIPIENT_ID, data_year2019$ffs_claims_2019$RECIPIENT_ID))) # 3694
#length(unique(intersect(intersect(demographic_2019_id, data_year2019$ffs_claims_2019$RECIPIENT_ID),data_year2019$hmo_claims_2019$RECIPIENT_ID ))) # 3694


# move to new plotting page 
grid.newpage() 

#draw.pairwise.venn(area1=56763, area2=59361,cross.area=3694, 
#                   category=c("HMO claims","FFS claims"),fill=c("#009999","red")) # https://www.geeksforgeeks.org/how-to-create-a-venn-diagram-in-r/


# create Venn diagram with three sets 
draw.triple.venn(area1=56763,area2=59361, area3 =1612620,  
                 n12=3694, n23=59360, n13=56763, n123=3694,  
                 category=c("HMO (2019)","FFS (2019)","Demographics (2019)"), 
                 col="red",fill=c("Green","Orange","Blue"), lty="solid", 
                 cat.cex = 1.3, cat.pos=c(0,0, 180), cat.col=c("Green","Orange","Blue"), cex=1.5) # cat.cex  the size of the category names; cex: A vector (length 7) giving the size of the areas' labels; cat.pos: position of category names https://www.rdocumentation.org/packages/VennDiagram/versions/1.7.3/topics/draw.triple.venn
#dev.off()


```




## unique ids split by number of visits 



```{r, message=F, warning=F}
hmo_2019=data_year2019$hmo_claims_2019
ffs_2019=data_year2019$ffs_claims_2019

FIRST_DATE_OF_SERVICE_converted_hmo=sapply(hmo_2019$FIRST_DATE_OF_SERVICE, convert_date)
FIRST_DATE_OF_SERVICE_converted_ffs=sapply(ffs_2019$FIRST_DATE_OF_SERVICE, convert_date)

hmo_2019_with_service_date_only=data.frame(RECIPIENT_ID=hmo_2019$RECIPIENT_ID, FIRST_DATE_OF_SERVICE_converted=FIRST_DATE_OF_SERVICE_converted_hmo) %>% distinct()  # remove duplicated rows that individuals have multiple rows at the same day 

ffs_2019_with_service_date_only=data.frame(RECIPIENT_ID=ffs_2019$RECIPIENT_ID, FIRST_DATE_OF_SERVICE_converted=FIRST_DATE_OF_SERVICE_converted_ffs) %>% distinct()
```




```{r, message=F, warning=F, eval=T}
hmo_table=table(hmo_2019_with_service_date_only$RECIPIENT_ID)
num_visit=seq(1,10)
count_id_hmo=function(x)
{sum(hmo_table==x)}
num_id_hmo=sapply(num_visit, count_id_hmo)
num_id_hmo[11]=sum(hmo_table>10)
visit_hmo=data.frame(num_visit=c(paste("0",num_visit[1:9], sep=""), "10", "more than 10"), num_id=num_id_hmo) %>% mutate(prop=round(num_id/sum(num_id_hmo),4))

#ggplot(visit_hmo, aes(x=num_visit, y=prop, fill=num_visit)) +geom_bar(stat="identity")+
#  ylim(c(0, 0.7))+
#  ylab("% unique ids")+xlab("number of visits in the year")+
#  theme(legend.position="none")+
#  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
#  geom_text(aes(label=num_id), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars
#  ggtitle("hmo (2019)")+
#  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 

# use rank function to rank multiple dates, then calculate the difference. 

```


```{r, message=F, warning=F, eval=T}
ffs_table=table(ffs_2019_with_service_date_only$RECIPIENT_ID)
num_visit=seq(1,10)
count_id_ffs=function(x)
{sum(ffs_table==x)}
num_id_ffs=sapply(num_visit, count_id_ffs)
num_id_ffs[11]=sum(ffs_table>10)
visit_ffs=data.frame(num_visit=c(paste("0",num_visit[1:9], sep=""), "10", "more than 10"), num_id=num_id_ffs) %>% mutate(prop=round(num_id/sum(num_id_ffs),4))

#ggplot(visit_ffs, aes(x=num_visit, y=prop, fill=num_visit)) +geom_bar(stat="identity")+
#  ylim(c(0, 0.7))+
#  ylab("% unique ids")+xlab("number of visits in the year")+
#  theme(legend.position="none")+
#  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
#  geom_text(aes(label=num_id), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars
#  ggtitle("ffs (2019)")+
#  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 

# use rank function to rank multiple dates, then calculate the difference. 

```


```{r, message=F, warning=F}
visit_ffs_and_hmo=rbind(visit_ffs, visit_hmo) %>%mutate(plan=rep(c("ffs", "hmo"), each=11))

ggplot(visit_ffs_and_hmo, aes(x=num_visit, y=prop, fill=plan)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, 0.7))+
  ylab("% unique ids")+xlab("number of visits in the year")+
  theme(legend.position="bottom")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=11))+
  geom_text(aes(label=num_id), position=position_dodge(width=0.9), vjust=-0.25, size=3)+  # add numbers over bars
  ggtitle("year 2019 ")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title

visit_ffs_and_hmo%>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



## unique ids split by time intervals 


```{r, message=F, warning=F, eval=F}
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
############ DONOT run as it takes too long time
hmo_unique_id=unique(hmo_2019_with_service_date_only$RECIPIENT_ID)
library(lubridate)
calculate_time_period_hmo=function(X)
{
  id_visit=hmo_2019_with_service_date_only %>% filter(RECIPIENT_ID ==X)
  if (nrow(id_visit)>1)
  {
    id_visit_rank=id_visit[order(id_visit$FIRST_DATE_OF_SERVICE_converted),] # https://stackoverflow.com/questions/6246159/how-to-sort-a-data-frame-by-date
    first_date_of_servie=id_visit_rank$FIRST_DATE_OF_SERVICE_converted[1]
    last_date_of_servide=id_visit_rank$FIRST_DATE_OF_SERVICE_converted[nrow(id_visit_rank)]
    time_period=difftime(last_date_of_servide,first_date_of_servie,units = "days")
    return(data.frame(id=id_visit$RECIPIENT_ID[1], first_date_of_servie=first_date_of_servie, last_date_of_servide=last_date_of_servide, time_period=time_period))
  }
  if (nrow(id_visit)==1)
  {
    
    first_date_of_servie=id_visit$FIRST_DATE_OF_SERVICE_converted[1]
    last_date_of_servide=id_visit$FIRST_DATE_OF_SERVICE_converted[1]
    time_period=difftime(last_date_of_servide,first_date_of_servie,units = "days")
    return(data.frame(id=id_visit$RECIPIENT_ID[1], first_date_of_servie=first_date_of_servie, last_date_of_servide=last_date_of_servide, time_period=time_period))
  }
  
}
time_preiod_visit_hmo=sapply(hmo_unique_id, calculate_time_period_hmo)
#saveRDS(t(time_preiod_visit_hmo), file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\hmo_2019_time_period_visit_20240515.rds")
```


```{r, message=F, warning=F, eval=F}
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
############ DONOT run as it takes too long time
ffs_unique_id=unique(ffs_2019_with_service_date_only$RECIPIENT_ID)
library(lubridate)
calculate_time_period_ffs=function(X)
{
  id_visit=ffs_2019_with_service_date_only %>% filter(RECIPIENT_ID ==X)
  if (nrow(id_visit)>1)
  {
    id_visit_rank=id_visit[order(id_visit$FIRST_DATE_OF_SERVICE_converted),]
    first_date_of_servie=id_visit_rank$FIRST_DATE_OF_SERVICE_converted[1]
    last_date_of_servide=id_visit_rank$FIRST_DATE_OF_SERVICE_converted[nrow(id_visit_rank)]
    time_period=difftime(last_date_of_servide,first_date_of_servie,units = "days")
    return(data.frame(id=id_visit$RECIPIENT_ID[1], first_date_of_servie=first_date_of_servie, last_date_of_servide=last_date_of_servide, time_period=time_period))
  }
  if (nrow(id_visit)==1)
  {
    
    first_date_of_servie=id_visit$FIRST_DATE_OF_SERVICE_converted[1]
    last_date_of_servide=id_visit$FIRST_DATE_OF_SERVICE_converted[1]
    time_period=difftime(last_date_of_servide,first_date_of_servie,units = "days")
    return(data.frame(id=id_visit$RECIPIENT_ID[1], first_date_of_servie=first_date_of_servie, last_date_of_servide=last_date_of_servide, time_period=time_period))
  }
  
}
time_preiod_visit_ffs=sapply(ffs_unique_id, calculate_time_period_ffs)
#saveRDS(t(time_preiod_visit_ffs), file="C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\ffs_2019_time_period_visit_20240515.rds")
```


```{r, message=F, warning=F}
hmo_2019_time_period_visit=readRDS("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\hmo_2019_time_period_visit_20240515.rds")
hmo_2019_time_period_visit1=data.frame(id=unlist(hmo_2019_time_period_visit[,1]), first_date_of_servie=unlist(hmo_2019_time_period_visit[,2]), last_date_of_service=unlist(hmo_2019_time_period_visit[,3]), time_period=unlist(hmo_2019_time_period_visit[,4]))
```



```{r, message=F, warning=F}
time_length=seq(30, 180, by=30); num_ids=numeric()
count_ids_hmo=function(x)
{
  hmo_2019_time_period_visit1 %>% filter(time_period>=x) %>% nrow()
  
}
num_ids=sapply(time_length, count_ids_hmo)

num_ids_hmo=data.frame(time_interval=paste(">=",seq(1,6), " month", sep=""), num_id=num_ids) %>% mutate(prop=round(num_id/nrow(hmo_2019_time_period_visit1),4))

#ggplot(num_ids_hmo, aes(x=time_interval, y=prop, fill=time_interval)) +geom_bar(stat="identity")+
#  ylim(c(0, 0.25))+
#  ylab("% No.unique ids")+xlab("time interval between the first and last visit")+
#  theme(legend.position="none")+
#  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
#  geom_text(aes(label=num_id), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars
#  ggtitle("hmo (2019)")+
#  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 


```


```{r, message=F, warning=F}
ffs_2019_time_period_visit=readRDS("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\CWFluoridationAnalysis\\ffs_2019_time_period_visit_20240515.rds")
ffs_2019_time_period_visit1=data.frame(id=unlist(ffs_2019_time_period_visit[,1]), first_date_of_servie=unlist(ffs_2019_time_period_visit[,2]), last_date_of_service=unlist(ffs_2019_time_period_visit[,3]), time_period=unlist(ffs_2019_time_period_visit[,4]))
```



```{r, message=F, warning=F}
time_length=seq(30, 180, by=30); num_ids=numeric()
count_ids_ffs=function(x)
{
  ffs_2019_time_period_visit1 %>% filter(time_period>=x) %>% nrow()
  
}
num_ids=sapply(time_length, count_ids_ffs)

num_ids_ffs=data.frame(time_interval=paste(">=",seq(1,6), " month", sep=""), num_id=num_ids) %>% mutate(prop=round(num_id/nrow(ffs_2019_time_period_visit1),4))

#ggplot(num_ids_ffs, aes(x=time_interval, y=prop, fill=time_interval)) +geom_bar(stat="identity")+
#  ylim(c(0, 0.4))+
#  ylab("% unique ids")+xlab("time interval between the first and last visit")+
#  theme(legend.position="none")+
#  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
#  geom_text(aes(label=num_id), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars
#  ggtitle("ffs (2019)")+
#  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 


```


```{r, message=F, warning=F}
num_ids_ffs_and_hmo=rbind(num_ids_ffs, num_ids_hmo)%>%mutate(plan=rep(c("ffs", "hmo"), each=nrow(num_ids_ffs)))
ggplot(num_ids_ffs_and_hmo, aes(x=time_interval, y=prop, fill=plan)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, 0.4))+
  ylab("% unique ids")+xlab("time interval between the first and last visit")+
  theme(legend.position="bottom")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  geom_text(aes(label=num_id), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars
  ggtitle("year 2019")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 

num_ids_ffs_and_hmo%>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


* denominator is total number of unique ids including ids with one visit 
